<x-layouts.app>
    <x-breadcrumb>Patrimônio / Movimentações / Nova</x-breadcrumb>
    <h1 class="mb-5 font-[Sora] text-2xl font-bold">Nova movimentação</h1>
    <form method="POST" action="{{ route('movements.store') }}" class="grid gap-5 lg:grid-cols-[1fr_22rem]">@csrf
        <div class="space-y-5">
            <x-form-section title="1. Ativo" description="Selecione o ativo a movimentar. A origem será derivada do estado atual."><x-select name="asset" label="Ativo" required><option value="">Selecione</option>@foreach($assets as $asset)<option value="{{ $asset->public_id }}" @selected(old('asset')===$asset->public_id)>{{ $asset->asset_number }} — {{ $asset->description }}</option>@endforeach</x-select></x-form-section>
            <x-form-section title="2. Tipo de movimentação" description="Somente tipos operacionais da Sprint 2 estão disponíveis."><x-select name="movement_type" label="Tipo" required><option value="">Selecione</option>@foreach($types as $type)<option value="{{ $type->value }}" @selected(old('movement_type')===$type->value)>{{ $type->label() }}</option>@endforeach</x-select></x-form-section>
            <x-form-section title="3. Destino ou responsável" description="Informe apenas o destino necessário para o tipo escolhido."><div class="grid gap-4 md:grid-cols-3"><x-select name="destination_organizational_unit" label="Unidade administrativa"><option value="">Manter atual</option>@foreach($organizationalUnits as $unit)<option value="{{ $unit->public_id }}" @selected(old('destination_organizational_unit')===$unit->public_id)>{{ $unit->name }}</option>@endforeach</x-select><x-select name="destination_location" label="Localização"><option value="">Sem localização</option>@foreach($locations as $location)<option value="{{ $location->public_id }}" @selected(old('destination_location')===$location->public_id)>{{ $location->name }}</option>@endforeach</x-select><x-select name="destination_custodian" label="Responsável"><option value="">Sem responsável</option>@foreach($custodians as $custodian)<option value="{{ $custodian->public_id }}" @selected(old('destination_custodian')===$custodian->public_id)>{{ $custodian->name }}</option>@endforeach</x-select></div></x-form-section>
            <x-form-section title="4. Datas" description="Use data prevista para empréstimos e saídas temporárias."><div class="grid gap-4 md:grid-cols-2"><x-input type="datetime-local" name="expected_return_at" label="Retorno previsto" value="{{ old('expected_return_at') }}" /><x-select name="related_movement" label="Movimentação de origem"><option value="">Não se aplica</option>@foreach($openReturns as $open)<option value="{{ $open->public_id }}" @selected(old('related_movement')===$open->public_id)>{{ $open->movement_type->label() }} — {{ $open->asset->asset_number }}</option>@endforeach</x-select></div></x-form-section>
            <x-form-section title="5. Motivo e observações" description="O motivo compõe o histórico imutável e os termos."><x-textarea name="reason" label="Motivo" required>{{ old('reason') }}</x-textarea><x-textarea name="notes" label="Observações">{{ old('notes') }}</x-textarea></x-form-section>
        </div>
        <x-card><h2 class="font-semibold">6. Revisão</h2><p class="mt-2 text-sm text-text-secondary">Confira os dados antes de registrar. A origem será lida do ativo no backend e não pode ser alterada pelo formulário.</p><div class="mt-5"><x-button>Registrar movimentação</x-button></div></x-card>
    </form>
</x-layouts.app>
