<x-layouts.app>
    <x-breadcrumb>Patrimônio / Movimentações</x-breadcrumb>
    <div class="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h1 class="font-[Sora] text-2xl font-bold">Movimentações</h1><p class="text-sm text-text-secondary">Histórico operacional de transferências, empréstimos e responsabilidades.</p></div>@can('create', App\Domain\Assets\Models\AssetMovement::class)<x-button type="button" onclick="location.href='{{ route('movements.create') }}'">Nova movimentação</x-button>@endcan</div>
    <x-filter-panel method="GET"><x-input name="asset_number" label="Número patrimonial" value="{{ request('asset_number') }}" /><x-select name="movement_type" label="Tipo"><option value="">Todos</option>@foreach($types as $type)<option value="{{ $type->value }}" @selected(request('movement_type')===$type->value)>{{ $type->label() }}</option>@endforeach</x-select><x-select name="status" label="Status"><option value="">Todos</option>@foreach(App\Domain\Assets\Enums\AssetMovementStatus::cases() as $status)<option value="{{ $status->value }}" @selected(request('status')===$status->value)>{{ $status->label() }}</option>@endforeach</x-select><x-input type="date" name="date_from" label="Data inicial" value="{{ request('date_from') }}" /><x-input type="date" name="date_to" label="Data final" value="{{ request('date_to') }}" /><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="overdue" value="1" @checked(request()->boolean('overdue'))> Retorno atrasado</label><x-button>Aplicar filtros</x-button><a class="px-3 py-2 text-sm text-teal-700" href="{{ route('movements.index') }}">Limpar filtros</a></x-filter-panel>
    <x-card class="mt-5"><x-table><thead><tr><th class="p-3">Ativo</th><th>Tipo</th><th>Status</th><th>Origem</th><th>Destino</th><th>Responsável</th><th>Data</th></tr></thead><tbody>
        @forelse($movements as $movement)<tr><td class="p-3"><a class="font-medium text-teal-700" href="{{ route('movements.show', $movement) }}">{{ $movement->asset->asset_number }}</a><div class="text-xs text-text-secondary">{{ $movement->asset->description }}</div></td><td>{{ $movement->movementType()->label() }}</td><td><x-badge>{{ $movement->movementStatus()->label() }}</x-badge></td><td>{{ $movement->originUnit?->name ?? '-' }}</td><td>{{ $movement->destinationUnit?->name ?? '-' }}</td><td>{{ $movement->destinationCustodian?->name ?? $movement->originCustodian?->name ?? '-' }}</td><td>{{ $movement->created_at->format('d/m/Y H:i') }}@if($movement->expected_return_at)<div class="text-xs {{ $movement->isReturnOverdue() ? 'text-red-700' : 'text-amber-700' }}">{{ $movement->isReturnOverdue() ? 'Atrasado' : 'Retorno previsto' }}: {{ $movement->expected_return_at->format('d/m/Y') }}</div>@endif</td></tr>@empty<tr><td colspan="7" class="p-8"><x-empty-state>Nenhuma movimentação encontrada. Use os filtros ou registre uma nova movimentação patrimonial.</x-empty-state></td></tr>@endforelse
    </tbody>
    </x-table><x-pagination :paginator="$movements" /></x-card>
</x-layouts.app>
