<x-layouts.app>
    <x-breadcrumb>Patrimônio / Movimentações / {{ $movement->public_id }}</x-breadcrumb>
    <div class="mb-5 flex flex-wrap items-start justify-between gap-3">
        <div><h1 class="font-[Sora] text-2xl font-bold">{{ $movement->movementType()->label() }}</h1><p class="text-sm text-text-secondary">{{ $movement->asset->asset_number }} — {{ $movement->asset->description }}</p></div>
        <x-badge>{{ $movement->movementStatus()->label() }}</x-badge>
    </div>
    <x-card><dl class="grid gap-4 text-sm md:grid-cols-2"><div><dt class="text-text-secondary">Origem</dt><dd class="font-medium">{{ $movement->originUnit?->name ?? '-' }} / {{ $movement->originLocation?->name ?? '-' }}</dd></div><div><dt class="text-text-secondary">Destino</dt><dd class="font-medium">{{ $movement->destinationUnit?->name ?? '-' }} / {{ $movement->destinationLocation?->name ?? '-' }}</dd></div><div><dt class="text-text-secondary">Responsável anterior</dt><dd class="font-medium">{{ $movement->originCustodian?->name ?? '-' }}</dd></div><div><dt class="text-text-secondary">Novo responsável</dt><dd class="font-medium">{{ $movement->destinationCustodian?->name ?? '-' }}</dd></div><div><dt class="text-text-secondary">Solicitante</dt><dd class="font-medium">{{ $movement->requester->name }}</dd></div><div><dt class="text-text-secondary">Aprovador</dt><dd class="font-medium">{{ $movement->approver?->name ?? '-' }}</dd></div><div><dt class="text-text-secondary">Retorno previsto</dt><dd class="font-medium">{{ $movement->expected_return_at?->format('d/m/Y H:i') ?? '-' }}</dd></div><div><dt class="text-text-secondary">Conclusão</dt><dd class="font-medium">{{ $movement->effective_at?->format('d/m/Y H:i') ?? '-' }}</dd></div><div class="md:col-span-2"><dt class="text-text-secondary">Motivo</dt><dd class="font-medium">{{ $movement->reason }}</dd></div><div class="md:col-span-2"><dt class="text-text-secondary">Observações</dt><dd class="font-medium">{{ $movement->notes ?? '-' }}</dd></div></dl><div class="mt-6 flex flex-wrap gap-3">@can('approve', $movement)<form method="POST" action="{{ route('movements.approve', $movement) }}">@csrf<x-button>Aprovar</x-button></form>@endcan @can('complete', $movement)<form method="POST" action="{{ route('movements.complete', $movement) }}">@csrf<x-button variant="secondary">Concluir</x-button></form>@endcan @can('reject', $movement)<form method="POST" action="{{ route('movements.reject', $movement) }}" onsubmit="return confirm('Rejeitar esta movimentação?')">@csrf<x-button variant="secondary">Rejeitar</x-button></form>@endcan @can('cancel', $movement)<form method="POST" action="{{ route('movements.cancel', $movement) }}" onsubmit="return confirm('Cancelar esta movimentação?')">@csrf<x-button variant="secondary">Cancelar</x-button></form>@endcan @can('generateTerm', $movement)<form method="POST" action="{{ route('movements.term', $movement) }}">@csrf<x-button variant="secondary">Gerar termo</x-button></form>@endcan @if($movement->termDocument)<a class="px-4 py-2 text-sm text-teal-700" href="{{ route('documents.download', $movement->termDocument) }}">Baixar termo</a>@endif</div></x-card>

    <x-card class="mt-5">
        <div class="mb-4 flex flex-wrap items-start justify-between gap-3"><div><h2 class="font-semibold">Documentos da movimentação</h2><p class="text-sm text-text-secondary">Termos, autorizações, comprovantes e fotografias ficam em storage privado.</p></div></div>
        @can('upload', App\Domain\Assets\Models\AssetMovementDocument::class)
            <form class="mb-5 grid gap-3 md:grid-cols-[14rem_1fr_auto]" method="POST" action="{{ route('movements.documents.store', $movement) }}" enctype="multipart/form-data">@csrf
                <x-select name="document_type" label="Tipo documental">@foreach($documentTypes as $type)<option value="{{ $type->value }}">{{ $type->label() }}</option>@endforeach</x-select>
                <label class="block text-sm font-medium">Arquivo PDF, PNG ou JPEG<input required name="file" type="file" accept="application/pdf,image/png,image/jpeg" class="mt-1 block w-full rounded-md border border-gray-300 text-sm"></label>
                <div class="flex items-end"><x-button>Adicionar documento</x-button></div>
            </form>
        @endcan
        <x-table><thead><tr><th class="p-3">Tipo</th><th>Nome</th><th>Data</th><th>Usuário</th><th>Tamanho</th><th>Ações</th></tr></thead><tbody>
            @forelse($movement->documents->whereNull('deactivated_at') as $link)<tr><td class="p-3">{{ $link->documentType()->label() }}</td><td>{{ $link->document->original_name }}</td><td>{{ $link->created_at->format('d/m/Y H:i') }}</td><td>{{ $link->uploader?->name ?? '-' }}</td><td>{{ number_format($link->document->size_bytes / 1024, 1, ',', '.') }} KB</td><td class="space-x-3"><a class="text-sm text-teal-700" href="{{ route('documents.view', $link->document) }}">Visualizar</a><a class="text-sm text-teal-700" href="{{ route('documents.download', $link->document) }}">Baixar</a>@can('deactivate', $link)<form class="inline" method="POST" action="{{ route('movements.documents.deactivate', $link) }}" onsubmit="return confirm('Inativar este documento da movimentação?')">@csrf @method('PATCH')<button class="text-sm text-red-700">Inativar</button></form>@endcan</td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-gray-500">Nenhum documento complementar foi anexado.</td></tr>@endforelse
        </tbody></x-table>
    </x-card>
</x-layouts.app>
