<?php

use App\Http\Controllers\AssetBrandController;
use App\Http\Controllers\AssetCategoryController;
use App\Http\Controllers\AssetConditionController;
use App\Http\Controllers\AssetController;
use App\Http\Controllers\AssetCustodianController;
use App\Http\Controllers\AssetCustomFieldDefinitionController;
use App\Http\Controllers\AssetModelController;
use App\Http\Controllers\AssetMovementController;
use App\Http\Controllers\AssetMovementDocumentController;
use App\Http\Controllers\AssetSelectionController;
use App\Http\Controllers\AssetTypeController;
use App\Http\Controllers\AuditLogController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Auth\NewPasswordController;
use App\Http\Controllers\Auth\PasswordResetLinkController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\InvitationController;
use App\Http\Controllers\LocationController;
use App\Http\Controllers\OrganizationalUnitController;
use App\Http\Controllers\PrivateDocumentController;
use App\Http\Controllers\PrivateDocumentUploadController;
use App\Http\Controllers\SessionController;
use App\Http\Controllers\TenantSelectionController;
use App\Http\Controllers\UnitOfMeasureController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/dashboard');
Route::middleware('guest')->group(function (): void {
    Route::get('/invitations/{invitation}/accept', [InvitationController::class, 'accept'])->name('invitations.accept');
    Route::post('/invitations/{invitation}/accept', [InvitationController::class, 'complete'])->name('invitations.complete');
    Route::get('/login', [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('/login', [AuthenticatedSessionController::class, 'store'])->middleware('throttle:login')->name('login.store');
    Route::get('/forgot-password', [PasswordResetLinkController::class, 'create'])->name('password.request');
    Route::post('/forgot-password', [PasswordResetLinkController::class, 'store'])->middleware('throttle:password.reset')->name('password.email');
    Route::get('/reset-password/{token}', [NewPasswordController::class, 'create'])->name('password.reset');
    Route::post('/reset-password', [NewPasswordController::class, 'store'])->middleware('throttle:password.reset')->name('password.update');
});
Route::middleware('auth')->group(function (): void {
    Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');
    Route::get('/sessions', [SessionController::class, 'index'])->name('sessions.index');
    Route::delete('/sessions/{session}', [SessionController::class, 'destroy'])->name('sessions.destroy');
    Route::delete('/sessions', [SessionController::class, 'destroyOthers'])->name('sessions.destroy-others');
    Route::put('/active-tenant', [TenantSelectionController::class, 'update'])->name('tenant.update');
    Route::middleware('tenant')->group(function (): void {
        Route::get('/invitations', [InvitationController::class, 'index'])->name('invitations.index');
        Route::get('/invitations/create', [InvitationController::class, 'create'])->name('invitations.create');
        Route::post('/invitations', [InvitationController::class, 'store'])->name('invitations.store');
        Route::post('/invitations/{invitation:public_id}/resend', [InvitationController::class, 'resend'])->name('invitations.resend');
        Route::get('/dashboard', DashboardController::class)->name('dashboard');
        Route::get('/catalog/categories', [AssetCategoryController::class, 'index'])->name('catalog.categories.index');
        Route::get('/catalog/categories/create', [AssetCategoryController::class, 'create'])->name('catalog.categories.create');
        Route::post('/catalog/categories', [AssetCategoryController::class, 'store'])->name('catalog.categories.store');
        Route::get('/catalog/categories/{category:public_id}/edit', [AssetCategoryController::class, 'edit'])->name('catalog.categories.edit');
        Route::put('/catalog/categories/{category:public_id}', [AssetCategoryController::class, 'update'])->name('catalog.categories.update');
        Route::patch('/catalog/categories/{category:public_id}/deactivate', [AssetCategoryController::class, 'deactivate'])->name('catalog.categories.deactivate');
        Route::get('/catalog/categories/{category:public_id}/children', [AssetCategoryController::class, 'children'])->name('catalog.categories.children');
        Route::resource('/catalog/types', AssetTypeController::class, ['as' => 'catalog'])->parameters(['types' => 'type:public_id'])->except(['destroy']);
        Route::patch('/catalog/types/{type:public_id}/deactivate', [AssetTypeController::class, 'deactivate'])->name('catalog.types.deactivate');
        Route::patch('/catalog/types/{type:public_id}/reactivate', [AssetTypeController::class, 'reactivate'])->name('catalog.types.reactivate');
        Route::resource('/catalog/brands', AssetBrandController::class, ['as' => 'catalog'])->parameters(['brands' => 'brand:public_id'])->except(['destroy']);
        Route::patch('/catalog/brands/{brand:public_id}/deactivate', [AssetBrandController::class, 'deactivate'])->name('catalog.brands.deactivate');
        Route::patch('/catalog/brands/{brand:public_id}/reactivate', [AssetBrandController::class, 'reactivate'])->name('catalog.brands.reactivate');
        Route::resource('/catalog/models', AssetModelController::class, ['as' => 'catalog'])->parameters(['models' => 'model:public_id'])->except(['destroy']);
        Route::patch('/catalog/models/{model:public_id}/deactivate', [AssetModelController::class, 'deactivate'])->name('catalog.models.deactivate');
        Route::patch('/catalog/models/{model:public_id}/reactivate', [AssetModelController::class, 'reactivate'])->name('catalog.models.reactivate');
        Route::resource('/catalog/units', UnitOfMeasureController::class, ['as' => 'catalog'])->parameters(['units' => 'unit:public_id'])->except(['destroy']);
        Route::patch('/catalog/units/{unit:public_id}/deactivate', [UnitOfMeasureController::class, 'deactivate'])->name('catalog.units.deactivate');
        Route::patch('/catalog/units/{unit:public_id}/reactivate', [UnitOfMeasureController::class, 'reactivate'])->name('catalog.units.reactivate');
        Route::resource('/catalog/conditions', AssetConditionController::class, ['as' => 'catalog'])->parameters(['conditions' => 'condition:public_id'])->except(['destroy']);
        Route::patch('/catalog/conditions/{condition:public_id}/deactivate', [AssetConditionController::class, 'deactivate'])->name('catalog.conditions.deactivate');
        Route::patch('/catalog/conditions/{condition:public_id}/reactivate', [AssetConditionController::class, 'reactivate'])->name('catalog.conditions.reactivate');
        Route::resource('/catalog/custom-fields', AssetCustomFieldDefinitionController::class, ['as' => 'catalog'])->parameters(['custom-fields' => 'field:public_id'])->except(['destroy']);
        Route::patch('/catalog/custom-fields/{field:public_id}/deactivate', [AssetCustomFieldDefinitionController::class, 'deactivate'])->name('catalog.custom-fields.deactivate');
        Route::patch('/catalog/custom-fields/{field:public_id}/reactivate', [AssetCustomFieldDefinitionController::class, 'reactivate'])->name('catalog.custom-fields.reactivate');
        Route::get('/assets', [AssetController::class, 'index'])->name('assets.index');
        Route::get('/assets/create', [AssetController::class, 'create'])->name('assets.create');
        Route::post('/assets', [AssetController::class, 'store'])->name('assets.store');
        Route::get('/assets/{asset:public_id}/edit', [AssetController::class, 'edit'])->name('assets.edit');
        Route::get('/assets/{asset:public_id}', [AssetController::class, 'show'])->name('assets.show');
        Route::put('/assets/{asset:public_id}', [AssetController::class, 'update'])->name('assets.update');
        Route::patch('/assets/{asset:public_id}/deactivate', [AssetController::class, 'deactivate'])->name('assets.deactivate');
        Route::patch('/assets/{asset:public_id}/reactivate', [AssetController::class, 'reactivate'])->name('assets.reactivate');
        Route::resource('/custodians', AssetCustodianController::class)->parameters(['custodians' => 'custodian:public_id'])->except(['show', 'destroy']);
        Route::patch('/custodians/{custodian:public_id}/deactivate', [AssetCustodianController::class, 'deactivate'])->name('custodians.deactivate');
        Route::get('/movements', [AssetMovementController::class, 'index'])->name('movements.index');
        Route::get('/movements/create', [AssetMovementController::class, 'create'])->name('movements.create');
        Route::post('/movements', [AssetMovementController::class, 'store'])->name('movements.store');
        Route::get('/movements/{movement:public_id}', [AssetMovementController::class, 'show'])->name('movements.show');
        Route::post('/movements/{movement:public_id}/approve', [AssetMovementController::class, 'approve'])->name('movements.approve');
        Route::post('/movements/{movement:public_id}/reject', [AssetMovementController::class, 'reject'])->name('movements.reject');
        Route::post('/movements/{movement:public_id}/cancel', [AssetMovementController::class, 'cancel'])->name('movements.cancel');
        Route::post('/movements/{movement:public_id}/complete', [AssetMovementController::class, 'complete'])->name('movements.complete');
        Route::post('/movements/{movement:public_id}/term', [AssetMovementController::class, 'generateTerm'])->name('movements.term');
        Route::post('/movements/{movement:public_id}/documents', [AssetMovementDocumentController::class, 'store'])->name('movements.documents.store');
        Route::patch('/movement-documents/{movementDocument:public_id}/deactivate', [AssetMovementDocumentController::class, 'deactivate'])->name('movements.documents.deactivate');
        Route::get('/asset-selections/types', [AssetSelectionController::class, 'types'])->name('asset-selections.types');
        Route::get('/asset-selections/models', [AssetSelectionController::class, 'models'])->name('asset-selections.models');
        Route::get('/asset-selections/locations', [AssetSelectionController::class, 'locations'])->name('asset-selections.locations');
        Route::get('/asset-selections/custom-fields', [AssetSelectionController::class, 'customFields'])->name('asset-selections.custom-fields');
        Route::get('/users', [UserController::class, 'index'])->name('users.index');
        Route::get('/users/create', [UserController::class, 'create'])->name('users.create');
        Route::post('/users', [UserController::class, 'store'])->name('users.store');
        Route::patch('/users/{user:public_id}/block', [UserController::class, 'block'])->name('users.block');
        Route::resource('units', OrganizationalUnitController::class)->except(['show', 'destroy']);
        Route::get('/locations', [LocationController::class, 'index'])->name('locations.index');
        Route::get('/locations/create', [LocationController::class, 'create'])->name('locations.create');
        Route::post('/locations', [LocationController::class, 'store'])->name('locations.store');
        Route::get('/locations/{location:public_id}/edit', [LocationController::class, 'edit'])->name('locations.edit');
        Route::put('/locations/{location:public_id}', [LocationController::class, 'update'])->name('locations.update');
        Route::get('/locations/{location:public_id}/children', [LocationController::class, 'children'])->name('locations.children');
        Route::get('/audit', [AuditLogController::class, 'index'])->name('audit.index');
        Route::get('/audit/{auditLog:public_id}', [AuditLogController::class, 'show'])->name('audit.show');
        Route::get('/documents/{document:public_id}/download', [PrivateDocumentController::class, 'download'])->name('documents.download');
        Route::get('/documents/{document:public_id}/view', [PrivateDocumentController::class, 'view'])->name('documents.view');
        Route::get('/documents', [PrivateDocumentUploadController::class, 'index'])->name('documents.index');
        Route::get('/documents/create', [PrivateDocumentUploadController::class, 'create'])->name('documents.create');
        Route::post('/documents', [PrivateDocumentUploadController::class, 'store'])->name('documents.store');
    });
});
